export const REQUEST_ALL_DOGS = 'REQUEST_ALL_DOGS';
export const RECIEVE_ALL_DOGS = 'RECIEVE_ALL_DOGS';
export const REQUEST_ADOPTION_STATUS = 'REQUEST_ADOPTION_STATUS';
export const RECIEVE_ADOPTION_STATUS = 'RECIEVE_ADOPTION_STATUS';
export const REQUEST_TO_ADOPT = 'REQUEST_TO_ADOPT';
export const RECIEVE_TO_ADOPT = 'RECIEVE_TO_ADOPT';
